### ISSUE TITLE
Module générique

### ISSUE THREAD

**Issue by ldesfontaine** [BaptisteGrauer/skazyrgpd#2]
Tu devrais rendre générique le module, genre retire tous ce qui est liée a skazy (nom de variable, fonctions etc...) .
Comme ça si un jour quelqu'un vient l'utiliser ca évitera qu'il est du code intitulé "skazy" dans sont prog ^^

**Comment by BaptisteGrauer** [comment]
peut-être mais là ce plugin c'est l'abandon

**Comment by ldesfontaine** [comment]
tktp je sais je mets juste ça la pour plus tars si ta envie de t'amuser et tous
